/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "callbcak.h"
#include <stdbool.h>
#include "kohill/fastconfig.h"
WM_HWIN hWin_AGC_PANEL;

extern GUI_CONST_STORAGE GUI_FONT GUI_FontHybrid16;
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/



// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "AGC_Panel", ID_FRAMEWIN_AGC_PANEL, 0, 0, 320, 240, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "增大增益", ID_BUTTON_UP, 0, 170, 116, 49, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "减小增益", ID_BUTTON_DOWN, 114, 171, 109, 49, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "切换至自动增益放大器", ID_BUTTON_SW, 220, 171, 93, 49, 0, 0x0, 0 },
  { SLIDER_CreateIndirect, "Slider", ID_SLIDER_0, 8, 50, 294, 54, 0, 0x0, 0 },

  { TEXT_CreateIndirect, "可变增益放大器控制面板", ID_TEXT_1, 122, 14, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "当前增益", ID_TEXT_2, 10, 125, 38, 33, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "0dB", ID_TEXT_GAIN, 143, 119, 141, 32, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
	  void hideAGC_Panel(void);

  WM_HWIN hItem;
  int     NCode;
  int     Id;
  uint16_t d= 0;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'AGC_Panel'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetFont(hItem, &GUI_FontHybrid16);
    //
    // Initialization of 'ButtonUp'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_UP);
    BUTTON_SetFont(hItem, &GUI_FontHybrid16);
    //
    // Initialization of 'ButtonDown'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_DOWN);
    BUTTON_SetFont(hItem, &GUI_FontHybrid16);
    //
    // Initialization of 'switch'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_SW);
    BUTTON_SetFont(hItem, &GUI_FontHybrid16);
    //
    // Initialization of 'labelTitle'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_TITLE);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, &GUI_FontHybrid16);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, &GUI_FontHybrid16);
    //
    // Initialization of 'TextCurrentGain'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, &GUI_FontHybrid16);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
    SLIDER_SetRange(hItem,0,2482);
    SLIDER_SetNumTicks(hItem,2483);

    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_UP: // Notifications sent by 'ButtonUp'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
    	  d=DAC_GetDataOutputValue(DAC_CH_AGC);
    	  if(d+10>=2581){
    		  break;
    	  }else{
        	  DAC_AGC_SET(d+10);
    	  }
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_DOWN: // Notifications sent by 'ButtonDown'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
    	  d= DAC_GetDataOutputValue(DAC_CH_AGC);
    	  if(d<10){
    		  break;
    	  }else{
        	  DAC_AGC_SET(d-10);
    	  }
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_SW: // Notifications sent by 'switch'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
//    	  GUI_EndDialog(hWin_AGC_PANEL,0);
//    	  WM_HWIN CreateFramewin(void);
//    	  CreateFramewin();
//    	  DMA_ITConfig(DMA2_Stream0,DMA_IT_TC,ENABLE);
    	  hideAGC_Panel();
    	  showDialog();
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SLIDER_0: // Notifications sent by 'Slider'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
    	  hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
    	  DAC_AGC_SET(SLIDER_GetValue(hItem));
        // USER START (Optionally insert code for reacting on notification message)
        // USER END

        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
  hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
  SLIDER_SetValue(hItem,DAC_GetDataOutputValue(DAC_CH_AGC));
  char buf[32];
  sprintf(buf,"%dV",DAC_GetDataOutputValue(DAC_CH_AGC));
  TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_GAIN),buf);
}



/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateAGC_Panel
*/
WM_HWIN CreateAGC_Panel(void);
WM_HWIN CreateAGC_Panel(void) {
	hWin_AGC_PANEL = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	return hWin_AGC_PANEL;
}
void hideAGC_Panel(void);
void showAGC_Panel(void);
void hideAGC_Panel(){
	WM_HideWindow(hWin_AGC_PANEL);
}
void showAGC_Panel(){
	WM_ShowWindow(hWin_AGC_PANEL);
}
// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
