#include "jianboqi.h"
#include "kohill/fastconfig.h"
#include <GUI.h>
#include <WM.h>
#include <stdio.h>
extern GUI_CONST_STORAGE GUI_FONT GUI_FontHybrid16;
extern GUI_CONST_STORAGE GUI_FONT GUI_FontHybrid24;
static WM_HWIN hWinDialog_AGC;
#define CTRL(x,mi,ma) if(x<=mi){x=mi;};if(x>=ma){x=ma;};

/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
static float desTV = 5.0f;
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0     (GUI_ID_USER + 0x00)
#define ID_TEXT_0     (GUI_ID_USER + 0x01)
#define ID_BUTTON_SW     (GUI_ID_USER + 0x02)
#define ID_CHECKBOX_0     (GUI_ID_USER + 0x03)
#define ID_TEXT_RMS     (GUI_ID_USER + 0x04)
#define ID_TEXT_1     (GUI_ID_USER + 0x06)
#define ID_TEXT_2     (GUI_ID_USER + 0x07)
#define ID_TEXT_3     (GUI_ID_USER + 0x08)
#define ID_TEXT_OUTPIT_VOL     (GUI_ID_USER + 0x010)
#define ID_TEXT_4     (GUI_ID_USER + 0x011)

#define ID_TEXT_VPP     (GUI_ID_USER + 0x09)
#define ID_BUTTON_UP     (GUI_ID_USER + 0x12)
#define ID_BUTTON_DE     (GUI_ID_USER + 0x13)
#define ID_SLIDER_V ((GUI_ID_USER + 0x14))
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 0, 0, 320, 240, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "自动增益放大器控制面板", ID_TEXT_3, 0, 20, 320, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "SWITCH", ID_BUTTON_SW, 220, 171, 93, 49, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_0, 110, 67, 150, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "峰峰值:", ID_TEXT_1, 6, 120, 320, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "2V", ID_TEXT_RMS, 100, 120, 80, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "有效值:", ID_TEXT_2, 6, 142, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Edit", ID_TEXT_VPP, 100, 142, 118, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "输出电压:", ID_TEXT_4, 6, 164, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "0.0V", ID_TEXT_OUTPIT_VOL, 100, 164, 118, 20, 0, 0x64, 0 },

  { BUTTON_CreateIndirect, "+25mV", ID_BUTTON_UP, 220, 220-3*32, 93, 32, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "-25mV", ID_BUTTON_DE, 220, 220-2*32, 93, 32, 0, 0x0, 0 },
  { SLIDER_CreateIndirect, "Sider", ID_SLIDER_V, 0, 220-4*32, 300, 32, 0, 0x0, 0 },

};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
	WM_HWIN hItem;
	int NCode;
	int Id;
	void hideDialog(void);

	// USER START (Optionally insert additional variables)
	// USER END

	switch (pMsg->MsgId) {
	case WM_INIT_DIALOG:
		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
		CHECKBOX_SetText(hItem, "Check");
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_RMS);
		TEXT_SetFont(hItem, &GUI_FontHybrid24);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		TEXT_SetFont(hItem, &GUI_FontHybrid24);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
		TEXT_SetFont(hItem, &GUI_FontHybrid24);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
		TEXT_SetFont(hItem, &GUI_FontHybrid24);
		TEXT_SetTextAlign(hItem, TEXT_CF_HCENTER | TEXT_CF_VCENTER);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_VPP);
		TEXT_SetFont(hItem, &GUI_FontHybrid24);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_OUTPIT_VOL);
		TEXT_SetFont(hItem, &GUI_FontHybrid24);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
		TEXT_SetFont(hItem, &GUI_FontHybrid24);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
		CHECKBOX_SetState(hItem, 1);
		CHECKBOX_SetFont(hItem, &GUI_FontHybrid24);
		CHECKBOX_SetText(hItem, "自动增益已经打开");
		CHECKBOX_SetTextColor(hItem, GUI_RED);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_V);
		SLIDER_SetNumTicks(hItem,6500);
		SLIDER_SetRange(hItem,0,6500);
		SLIDER_SetValue(hItem,(int)desTV*1000);
		break;
	case WM_NOTIFY_PARENT:
		Id = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;
		switch (Id) {
		case ID_BUTTON_SW: // Notifications sent by 'SWITCH'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				hideDialog();
				void showAGC_Panel(void);
				showAGC_Panel();
				break;
			}
			break;

		case ID_BUTTON_UP: // Notifications sent by 'SWITCH'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_V);
				desTV += 0.025f;
				CTRL(desTV,0,7.5);
				SLIDER_SetValue(hItem,(int)(desTV*1000));
				break;
			}
			break;
		case ID_BUTTON_DE: // Notifications sent by 'SWITCH'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_V);
				desTV -= 0.025f;
				CTRL(desTV,0,7.5);
				SLIDER_SetValue(hItem,(int)(desTV*1000));
				break;
			}
			break;
		case ID_CHECKBOX_0: // Notifications sent by 'Checkbox'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				hItem=WM_GetDialogItem(hWinDialog_AGC,ID_CHECKBOX_0);
				if(CHECKBOX_GetState(hItem)){
					CHECKBOX_SetText(hItem,"自动增益开");
				}
				else{
					CHECKBOX_SetText(hItem,"自动增益关");
				}
				break;
			}
			break;
		case ID_SLIDER_V: // Notifications sent by 'Checkbox'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_V);
				desTV = 1.0f*SLIDER_GetValue(hItem)/1000;
				break;
			}
			break;

		case ID_TEXT_RMS: // Notifications sent by 'Edit'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_TEXT_VPP: // Notifications sent by 'Edit'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
			// USER START (Optionally insert additional code for further Ids)
			// USER END
		}
		break;

	default:
		WM_DefaultProc(pMsg);
		break;

	}
	char buf[32];
	sprintf(buf,"%f",desTV);
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_OUTPIT_VOL);
	TEXT_SetText(hItem,buf);

}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/


WM_HWIN CreateFramewin(void);
WM_HWIN CreateFramewin(void) {

	hWinDialog_AGC = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	GUI_SetFont(&GUI_FontHybrid16);
  return hWinDialog_AGC;
}
void showVppVrmsVg(float vpp,float vrms,float Vgt);
void showVppVrmsVg(float vpp,float vrms,float Vgt){
	WM_HWIN hItem;

	char buf[32];
	hItem=WM_GetDialogItem(hWinDialog_AGC,ID_TEXT_RMS);
	sprintf(buf,"Vpp%.2fV",vpp);
	TEXT_SetText(hItem,buf);

	hItem=WM_GetDialogItem(hWinDialog_AGC,ID_TEXT_VPP);
	sprintf(buf,"Vrms:%.2fV",vrms);
	TEXT_SetText(hItem,buf);

	hItem=WM_GetDialogItem(hWinDialog_AGC,ID_TEXT_OUTPIT_VOL);
	sprintf(buf,"VoutSet:%.2fV",Vgt);
	TEXT_SetText(hItem,buf);


}

#include <stdio.h>
#include <stdint.h>
float getRms(float dacV,float  Vpp);
const float rmsTable[] = { 10, -0.5, 50, -0.495, 100, -0.495, 200, -0.49, 300,
		-0.483, 400, -0.479, 500, -0.46, 600, -0.43, 700, -0.352, 800, -0.2,
		900, 0.095, 950, 0.3, 980, 0.45, 1000, 0.59, 1030, 0.79, 1050, 0.94,
		1080, 1.24, 1100, 1.43, 1150, 2, 1180, 2.4, 1200, 2.6, 1230, 3 };
#include <math.h>
float getRms(float dacV,float  Vpp){
	float rms = 0;
	for(int i = 0;i<sizeof(rmsTable)/sizeof(rmsTable[0])-3;i+=2){
		if(dacV>rmsTable[i] && dacV<rmsTable[i+2]){
			rms=  (rmsTable[i+3]-rmsTable[i+1])/(rmsTable[i+2]-rmsTable[i])*(dacV-rmsTable[i]) + rmsTable[i+1];
			return sqrt((rms*rms + Vpp*Vpp/8))-0.15;
		}
	}
	if(dacV<=10){
		rms  = -0.5;
	}
	else rms = 3.0f;

	return rms + Vpp/1.414;
}

static uint16_t JIANBO_ADC_BUFFER[JIANBO_POINTS_COUNTS];
static WM_HWIN dialog;
void jianboqi_init(){
	k_ADC_Ch12_DMA_Fast_Config_12it(JIANBO_POINTS_COUNTS,&JIANBO_ADC_BUFFER[0]);//ADC��ʼ����12bit
	dialog = CreateFramewin();
	k_TIM_Fast_Config(TIM2,840,100,ENABLE);
	TIM_Cmd(TIM2,ENABLE);
}
void hideDialog(void);
void hideDialog(void){
	WM_HideWindow(dialog);
}
void showDialog(void);
void showDialog(){
	WM_ShowWindow(dialog);
}
void TIM2_IRQHandler(void);
void TIM2_IRQHandler(void){
	TIM_Cmd(TIM3,ENABLE);
	TIM_ClearITPendingBit(TIM2,TIM_IT_Update);

}
static inline float f(float x){
//	return  0.2247f*x+0.059f;
	return (x+0.1236)/(4.4477);
}
#include <stdio.h>
static float k = 0.001f;
static float integer = 0.0f,Ki = 0.02;
void DMA2_Stream0_IRQHandler(void);
void DMA2_Stream0_IRQHandler(void) {
	uint32_t sumj = 0;
	for(int i = 0;i<JIANBO_POINTS_COUNTS;i++){
		sumj+=JIANBO_ADC_BUFFER[i];
	}
	volatile float v = 1.0f*sumj/JIANBO_POINTS_COUNTS/4095*3.3;
	float destV = f(desTV);
	CTRL(destV,0,1.3);
	float errorCu = destV-v;
//	float errorCu = 1.14f-v;

	integer += errorCu;
	CTRL(integer,-200.0f,200.0f);
	float Vg = k*errorCu +Ki* integer;
	CTRL(Vg,0,2);
	WM_HWIN hItem=WM_GetDialogItem(hWinDialog_AGC,ID_CHECKBOX_0);
	if(CHECKBOX_GetState(hItem)){
		DAC_SetChannel2Data(DAC_Align_12b_R,(uint16_t)(Vg/3.3f*4095));
	}
	DMA_ClearITPendingBit(DMA2_Stream0, DMA_IT_TCIF0);
	TIM_Cmd(TIM3,DISABLE);
	showVppVrmsVg(4.4477f*v-0.1236f,getRms(DAC_GetDataOutputValue(DAC_Channel_2),4.4487f*v-0.1236f),desTV);

	char buf[32];
	hItem=WM_GetDialogItem(hWinDialog_AGC,ID_TEXT_4);
	sprintf(buf,"Me:%.2fV",v);
	TEXT_SetText(hItem,buf);


}
