/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Light16.c                                             *
* Font:        YaHei Consolas Hybrid                                 *
* Height:      14                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  14                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\yks\Desktop\新建文本文档.txt           *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontLight16;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0021[  8] = { /* code 0021, EXCLAMATION MARK */
  XX______,
  XX______,
  _X______,
  X_______,
  X_______,
  ________,
  ________,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0022[  3] = { /* code 0022, QUOTATION MARK */
  XXXX____,
  XX_X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0023[  7] = { /* code 0023, NUMBER SIGN */
  __X_X___,
  __X_X___,
  _X_XX___,
  _X_X____,
  XXXXXX__,
  _X_X____,
  _X_X____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0024[  9] = { /* code 0024, DOLLAR SIGN */
  __X_____,
  XXXX____,
  X_X_____,
  XX______,
  _XX_____,
  _X_X____,
  _X_X____,
  XXXX____,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0025[  8] = { /* code 0025, PERCENT SIGN */
  _X___X__,
  X_X_X___,
  X_X_X___,
  _X_X____,
  __X_____,
  __XXXX__,
  _X_X_X__,
  X__XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0026[  7] = { /* code 0026, AMPERSAND */
  _XXX____,
  _X__X___,
  _X_X____,
  _XX_X___,
  X__XX___,
  X___X___,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0027[  3] = { /* code 0027, APOSTROPHE */
  XX______,
  XX______,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0028[ 10] = { /* code 0028, LEFT PARENTHESIS */
  __X_____,
  _X______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  _X______,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0029[ 10] = { /* code 0029, RIGHT PARENTHESIS */
  X_______,
  _X______,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  _X______,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_002A[  5] = { /* code 002A, ASTERISK */
  ________,
  XX_X____,
  _XX_____,
  XX_X____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_002B[  6] = { /* code 002B, PLUS SIGN */
  ________,
  __X_____,
  __X_____,
  _XXXX___,
  __X_____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_002C[  4] = { /* code 002C, COMMA */
  _XX_____,
  _XX_____,
  __X_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_002D[  1] = { /* code 002D, HYPHEN-MINUS */
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_002E[  2] = { /* code 002E, FULL STOP */
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_002F[  8] = { /* code 002F, SOLIDUS */
  _____X__,
  ____X___,
  ____X___,
  ___X____,
  __X_____,
  __X_____,
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0030[  7] = { /* code 0030, DIGIT ZERO */
  _XXXX___,
  _X__X___,
  X___XX__,
  X_XX_X__,
  _X___X__,
  _X__X___,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0031[  7] = { /* code 0031, DIGIT ONE */
  _XX_____,
  X_X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0032[  7] = { /* code 0032, DIGIT TWO */
  XXXX____,
  ___X____,
  ___X____,
  __XX____,
  _XX_____,
  XX______,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0033[  7] = { /* code 0033, DIGIT THREE */
  XXXX____,
  ___X____,
  ___X____,
  _XX_____,
  ___X____,
  ___X____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0034[  7] = { /* code 0034, DIGIT FOUR */
  ___XX___,
  __X_X___,
  __X_X___,
  _X__X___,
  X___X___,
  _XXXX___,
  ____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0035[  7] = { /* code 0035, DIGIT FIVE */
  XXXX____,
  X_______,
  X_______,
  XXXX____,
  ___X____,
  ___X____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0036[  7] = { /* code 0036, DIGIT SIX */
  _XXX____,
  X_______,
  X_______,
  XXXX____,
  X__X____,
  X__X____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0037[  7] = { /* code 0037, DIGIT SEVEN */
  XXXX____,
  ___X____,
  ___X____,
  __X_____,
  __X_____,
  _X______,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0038[  7] = { /* code 0038, DIGIT EIGHT */
  XXXX____,
  X__X____,
  X__X____,
  _XX_____,
  X__X____,
  X__X____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0039[  7] = { /* code 0039, DIGIT NINE */
  XXXX____,
  X__X____,
  X__X____,
  X_XX____,
  _X_X____,
  ___X____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_003A[  5] = { /* code 003A, COLON */
  XX______,
  ________,
  ________,
  ________,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_003B[  7] = { /* code 003B, SEMICOLON */
  _XX_____,
  ________,
  ________,
  _XX_____,
  _XX_____,
  __X_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_003C[  6] = { /* code 003C, LESS-THAN SIGN */
  ___X____,
  __X_____,
  XX______,
  XX______,
  _XX_____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_003D[  2] = { /* code 003D, EQUALS SIGN */
  XXXX____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_003E[  6] = { /* code 003E, GREATER-THAN SIGN */
  X_______,
  _X______,
  __XX____,
  ___X____,
  _XX_____,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_003F[  8] = { /* code 003F, QUESTION MARK */
  X_______,
  _X______,
  __X_____,
  __X_____,
  XX______,
  X_______,
  ________,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0040[ 10] = { /* code 0040, COMMERCIAL AT */
  ___X____,
  _XX_X___,
  _X___X__,
  X_XXXX__,
  X_XX_X__,
  XX_X_X__,
  XX_X_X__,
  X_X_X___,
  X_______,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0041[  7] = { /* code 0041, LATIN CAPITAL LETTER A */
  __XX____,
  __XX____,
  _X__X___,
  _X__X___,
  _X__X___,
  _XXXXX__,
  X____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0042[  7] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXX____,
  X__X____,
  X__X____,
  XXXX____,
  X__X____,
  X__X____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0043[  7] = { /* code 0043, LATIN CAPITAL LETTER C */
  __XXX___,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0044[  7] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXX_____,
  X__X____,
  X___X___,
  X___X___,
  X___X___,
  X__X____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0045[  7] = { /* code 0045, LATIN CAPITAL LETTER E */
  XXXX____,
  X_______,
  X_______,
  XXXX____,
  X_______,
  X_______,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0046[  7] = { /* code 0046, LATIN CAPITAL LETTER F */
  XXXX____,
  X_______,
  X_______,
  XXXX____,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0047[  7] = { /* code 0047, LATIN CAPITAL LETTER G */
  __XXX___,
  _X______,
  X_______,
  X__XX___,
  X___X___,
  _X__X___,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0048[  7] = { /* code 0048, LATIN CAPITAL LETTER H */
  X__X____,
  X__X____,
  X__X____,
  XXXX____,
  X__X____,
  X__X____,
  X__X____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0049[  7] = { /* code 0049, LATIN CAPITAL LETTER I */
  XXXX____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_004A[  7] = { /* code 004A, LATIN CAPITAL LETTER J */
  XXXX____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_004B[  7] = { /* code 004B, LATIN CAPITAL LETTER K */
  X__X____,
  X_X_____,
  XX______,
  XX______,
  X_X_____,
  X_X_____,
  X__X____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_004C[  7] = { /* code 004C, LATIN CAPITAL LETTER L */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_004D[  7] = { /* code 004D, LATIN CAPITAL LETTER M */
  _X__X___,
  _X_X_X__,
  X_XX_X__,
  X_XX_X__,
  X____X__,
  X____X__,
  X____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_004E[  7] = { /* code 004E, LATIN CAPITAL LETTER N */
  X_______,
  XX_X____,
  XX_X____,
  X_XX____,
  X_XX____,
  X_XX____,
  X__X____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_004F[  7] = { /* code 004F, LATIN CAPITAL LETTER O */
  _XXXX___,
  _X__X___,
  X____X__,
  X____X__,
  X____X__,
  _X__X___,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0050[  7] = { /* code 0050, LATIN CAPITAL LETTER P */
  XXXX____,
  X__X____,
  X__X____,
  X__X____,
  XXX_____,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0051[  9] = { /* code 0051, LATIN CAPITAL LETTER Q */
  _XXXX___,
  _X__X___,
  X____X__,
  X____X__,
  X____X__,
  _X__X___,
  _XXXX___,
  ___X____,
  ___XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0052[  7] = { /* code 0052, LATIN CAPITAL LETTER R */
  XXXX____,
  X__X____,
  X__X____,
  XXX_____,
  X_X_____,
  X__X____,
  X__X____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0053[  7] = { /* code 0053, LATIN CAPITAL LETTER S */
  XXXX____,
  X_______,
  X_______,
  _XX_____,
  ___X____,
  ___X____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0054[  7] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXXX__,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0055[  7] = { /* code 0055, LATIN CAPITAL LETTER U */
  X_______,
  X__X____,
  X__X____,
  X__X____,
  X__X____,
  X__X____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0056[  7] = { /* code 0056, LATIN CAPITAL LETTER V */
  X____X__,
  _X___X__,
  _X__X___,
  _X__X___,
  __XX____,
  __XX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0057[  7] = { /* code 0057, LATIN CAPITAL LETTER W */
  X____X__,
  X____X__,
  X____X__,
  X_XX_X__,
  X_XX_X__,
  XX_XX___,
  _X__X___};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0058[  7] = { /* code 0058, LATIN CAPITAL LETTER X */
  _X__X___,
  _X__X___,
  __XX____,
  __XX____,
  __XX____,
  _X__X___,
  XX__XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0059[  7] = { /* code 0059, LATIN CAPITAL LETTER Y */
  X____X__,
  _X__X___,
  _XX_X___,
  __XX____,
  ___X____,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_005A[  7] = { /* code 005A, LATIN CAPITAL LETTER Z */
  XXXX____,
  ___X____,
  __X_____,
  _XX_____,
  _X______,
  X_______,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_005B[ 10] = { /* code 005B, LEFT SQUARE BRACKET */
  XXX_____,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_005C[  9] = { /* code 005C, REVERSE SOLIDUS */
  X_______,
  X_______,
  _X______,
  _X______,
  _X______,
  __X_____,
  __X_____,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_005D[ 10] = { /* code 005D, RIGHT SQUARE BRACKET */
  XX______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_005E[  3] = { /* code 005E, CIRCUMFLEX ACCENT */
  _XX_____,
  _XX_____,
  X__X____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_005F[  1] = { /* code 005F, LOW LINE */
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0060[  2] = { /* code 0060, GRAVE ACCENT */
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0061[  5] = { /* code 0061, LATIN SMALL LETTER A */
  XXXX____,
  ___X____,
  XXXX____,
  X__X____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0062[  8] = { /* code 0062, LATIN SMALL LETTER B */
  X_______,
  X_______,
  X_______,
  XXXX____,
  X__X____,
  X__X____,
  X__X____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0063[  5] = { /* code 0063, LATIN SMALL LETTER C */
  XXXX____,
  X_______,
  X_______,
  X_______,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0064[  8] = { /* code 0064, LATIN SMALL LETTER D */
  ___X____,
  ___X____,
  ___X____,
  XXXX____,
  X__X____,
  X__X____,
  X__X____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0065[  5] = { /* code 0065, LATIN SMALL LETTER E */
  XXXX____,
  X__X____,
  XXXX____,
  X_______,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0066[  8] = { /* code 0066, LATIN SMALL LETTER F */
  ___XXX__,
  __X_____,
  __X_____,
  XXXXX___,
  __X_____,
  __X_____,
  __X_____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0067[  7] = { /* code 0067, LATIN SMALL LETTER G */
  _XXXX___,
  _X__X___,
  _XXXX___,
  _X______,
  _XXXX___,
  _X___X__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0068[  8] = { /* code 0068, LATIN SMALL LETTER H */
  X_______,
  X_______,
  X_______,
  XXXX____,
  X__X____,
  X__X____,
  X__X____,
  X__X____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0069[  8] = { /* code 0069, LATIN SMALL LETTER I */
  ________,
  _XX_____,
  ________,
  _XX_____,
  __X_____,
  __X_____,
  __X_____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_006A[ 10] = { /* code 006A, LATIN SMALL LETTER J */
  __X_____,
  __XX____,
  ________,
  _XXX____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __X_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_006B[  8] = { /* code 006B, LATIN SMALL LETTER K */
  X_______,
  X_______,
  X_______,
  X_XX____,
  XXX_____,
  XX______,
  X_X_____,
  X__X____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_006C[  8] = { /* code 006C, LATIN SMALL LETTER L */
  XXX_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_006D[  5] = { /* code 006D, LATIN SMALL LETTER M */
  XXXXXX__,
  X_X__X__,
  X_X__X__,
  X_X__X__,
  X____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_006E[  5] = { /* code 006E, LATIN SMALL LETTER N */
  XXXX____,
  X__X____,
  X__X____,
  X__X____,
  X__X____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_006F[  5] = { /* code 006F, LATIN SMALL LETTER O */
  _XXXX___,
  _X__X___,
  X____X__,
  _X__X___,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0070[  7] = { /* code 0070, LATIN SMALL LETTER P */
  XXXX____,
  X__X____,
  X__X____,
  X__X____,
  XXXX____,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0071[  7] = { /* code 0071, LATIN SMALL LETTER Q */
  XXXX____,
  X__X____,
  X__X____,
  X__X____,
  XXXX____,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0072[  5] = { /* code 0072, LATIN SMALL LETTER R */
  XXXX____,
  X___X___,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0073[  5] = { /* code 0073, LATIN SMALL LETTER S */
  XXXX____,
  X_______,
  _XXX____,
  ___X____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0074[  7] = { /* code 0074, LATIN SMALL LETTER T */
  __X_____,
  __X_____,
  _XXX____,
  __X_____,
  __X_____,
  __X_____,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0075[  5] = { /* code 0075, LATIN SMALL LETTER U */
  X__X____,
  X__X____,
  X__X____,
  X__X____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0076[  5] = { /* code 0076, LATIN SMALL LETTER V */
  _X__X___,
  _X__X___,
  _X__X___,
  __XX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0077[  5] = { /* code 0077, LATIN SMALL LETTER W */
  X____X__,
  X_XX_X__,
  X_XXX___,
  _XXXX___,
  _X__X___};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0078[  5] = { /* code 0078, LATIN SMALL LETTER X */
  _X__X___,
  __XX____,
  __XX____,
  __XXX___,
  _X__X___};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0079[  7] = { /* code 0079, LATIN SMALL LETTER Y */
  _X__X___,
  _X__X___,
  __X_X___,
  __XX____,
  __XX____,
  __X_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_007A[  5] = { /* code 007A, LATIN SMALL LETTER Z */
  _XXX____,
  __X_____,
  _X______,
  _X______,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_007B[ 10] = { /* code 007B, LEFT CURLY BRACKET */
  __XX____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_007C[ 11] = { /* code 007C, VERTICAL LINE */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_007D[ 10] = { /* code 007D, RIGHT CURLY BRACKET */
  XX______,
  __X_____,
  __X_____,
  __X_____,
  __XX____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_007E[  2] = { /* code 007E, TILDE */
  _XX__X__,
  X__XX___};

/* Start of unicode area <Latin-1 Supplement> */
GUI_CONST_STORAGE unsigned char acGUI_FontLight16_00A4[  7] = { /* code 00A4, CURRENCY SIGN */
  X___X___,
  XXXXX___,
  X___X___,
  X___X___,
  X___X___,
  XXXXX___,
  X___X___};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_00A7[  9] = { /* code 00A7, SECTION SIGN */
  _XXX____,
  X_______,
  XX______,
  X_XX____,
  X__X____,
  XX_X____,
  __X_____,
  ___X____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_00A8[  1] = { /* code 00A8, DIAERESIS */
  X_X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_00B0[  3] = { /* code 00B0, DEGREE SIGN */
  XXX_____,
  X_X_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_00B1[  7] = { /* code 00B1, PLUS-MINUS SIGN */
  __X_____,
  __X_____,
  XXXXX___,
  __X_____,
  __X_____,
  ________,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_00B7[  1] = { /* code 00B7, MIDDLE DOT */
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_00D7[  5] = { /* code 00D7, MULTIPLICATION SIGN */
  X___X___,
  _X_X____,
  __X_____,
  _X_X____,
  X___X___};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_00E0[  8] = { /* code 00E0, LATIN SMALL LETTER A WITH GRAVE */
  X_______,
  X_______,
  ________,
  XXXX____,
  ___X____,
  XXXX____,
  X__X____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_00E1[  9] = { /* code 00E1, LATIN SMALL LETTER A WITH ACUTE */
  __X_____,
  _X______,
  ________,
  ________,
  XXXX____,
  ___X____,
  XXXX____,
  X__X____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_00E8[ 10] = { /* code 00E8, LATIN SMALL LETTER E WITH GRAVE */
  _X______,
  _X______,
  ________,
  __X_____,
  __X_____,
  XX_X____,
  X__X____,
  XXXX____,
  X_______,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_00E9[ 11] = { /* code 00E9, LATIN SMALL LETTER E WITH ACUTE */
  ___X____,
  __X_____,
  ________,
  ________,
  ___X____,
  __XX____,
  XX_X____,
  X__X____,
  XXXX____,
  X_______,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_00EA[  9] = { /* code 00EA, LATIN SMALL LETTER E WITH CIRCUMFLEX */
  X_______,
  XX______,
  ________,
  ________,
  XXXX____,
  X__X____,
  XXXX____,
  X_______,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_00EC[  9] = { /* code 00EC, LATIN SMALL LETTER I WITH GRAVE */
  X_______,
  X_______,
  ________,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_00ED[  9] = { /* code 00ED, LATIN SMALL LETTER I WITH ACUTE */
  _X______,
  X_______,
  ________,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_00F2[  8] = { /* code 00F2, LATIN SMALL LETTER O WITH GRAVE */
  ____X___,
  ____X___,
  ________,
  _XXXX___,
  _X__X___,
  X____X__,
  _X__X___,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_00F3[  9] = { /* code 00F3, LATIN SMALL LETTER O WITH ACUTE */
  _____X__,
  ____X___,
  ________,
  ________,
  _XXXX___,
  _X__X___,
  X____X__,
  _X__X___,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_00F7[  5] = { /* code 00F7, DIVISION SIGN */
  __X_____,
  ________,
  XXXXX___,
  ________,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_00F9[  8] = { /* code 00F9, LATIN SMALL LETTER U WITH GRAVE */
  X_______,
  X_______,
  ________,
  X__X____,
  X__X____,
  X_XX____,
  X__X____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_00FA[  9] = { /* code 00FA, LATIN SMALL LETTER U WITH ACUTE */
  __X_____,
  _X______,
  ________,
  ________,
  X__X____,
  X__X____,
  X_XX____,
  X__X____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_00FC[  7] = { /* code 00FC, LATIN SMALL LETTER U WITH DIAERESIS */
  X_X_____,
  ________,
  X__X____,
  X__X____,
  X__X____,
  X__X____,
  XXXX____};

/* Start of unicode area <Latin Extended-A> */
GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0101[  8] = { /* code 0101, LATIN SMALL LETTER A WITH MACRON */
  _XXXX___,
  ________,
  ________,
  XXXX____,
  ___X____,
  XXXX____,
  X__X____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0113[ 10] = { /* code 0113, LATIN SMALL LETTER E WITH MACRON */
  XXXX____,
  ________,
  ________,
  ___X____,
  ___X____,
  _XX_X___,
  _X__X___,
  _XXXX___,
  _X______,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_011B[ 11] = { /* code 011B, LATIN SMALL LETTER E WITH CARON */
  _X_X____,
  __X_____,
  ________,
  ________,
  ___X____,
  __XX____,
  XX_X____,
  X__X____,
  XXXX____,
  X_______,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_012B[  8] = { /* code 012B, LATIN SMALL LETTER I WITH MACRON */
  XXXX____,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0144[  9] = { /* code 0144, LATIN SMALL LETTER N WITH ACUTE */
  ____X___,
  ___X____,
  ________,
  ________,
  XXXX____,
  XX_X____,
  X__X____,
  X__X____,
  X__X____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0148[  9] = { /* code 0148, LATIN SMALL LETTER N WITH CARON */
  __X_X___,
  ___X____,
  ________,
  ________,
  XXXX____,
  X__X____,
  X__X____,
  X__X____,
  XX_X____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_014D[  8] = { /* code 014D, LATIN SMALL LETTER O WITH MACRON */
  ___XXXX_,
  ________,
  ________,
  _XXXX___,
  _X__X___,
  X____X__,
  _X__X___,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_016B[  8] = { /* code 016B, LATIN SMALL LETTER U WITH MACRON */
  XXXX____,
  ________,
  ________,
  _X__X___,
  _X__X___,
  _X_XX___,
  _X__X___,
  _XXXX___};

/* Start of unicode area <Latin Extended-B> */
GUI_CONST_STORAGE unsigned char acGUI_FontLight16_01CE[  9] = { /* code 01CE, LATIN SMALL LETTER A WITH CARON */
  _X_X____,
  __X_____,
  ________,
  ________,
  XXXX____,
  ___X____,
  XXXX____,
  X__X____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_01D0[  9] = { /* code 01D0, LATIN SMALL LETTER I WITH CARON */
  X_X_____,
  _X______,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_01D2[  9] = { /* code 01D2, LATIN SMALL LETTER O WITH CARON */
  ___X_X__,
  ____X___,
  ________,
  ________,
  _XXXX___,
  _X__X___,
  X____X__,
  _X__X___,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_01D4[  9] = { /* code 01D4, LATIN SMALL LETTER U WITH CARON */
  _X_X____,
  __X_____,
  ________,
  ________,
  X__X____,
  X__X____,
  X__X____,
  X__X____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_01D6[ 10] = { /* code 01D6, LATIN SMALL LETTER U WITH DIAERESIS AND MACRON */
  XXXX____,
  ________,
  _X_X____,
  ________,
  ________,
  X__X____,
  X__X____,
  X__X____,
  X__X____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_01D8[ 11] = { /* code 01D8, LATIN SMALL LETTER U WITH DIAERESIS AND ACUTE */
  ___X____,
  __X_____,
  ________,
  _X_X____,
  ________,
  ________,
  X__X____,
  X__X____,
  X__X____,
  X__X____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_01DA[ 11] = { /* code 01DA, LATIN SMALL LETTER U WITH DIAERESIS AND CARON */
  _X_X____,
  __X_____,
  ________,
  _X_X____,
  ________,
  ________,
  X__X____,
  X__X____,
  X__X____,
  X__X____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_01DC[ 10] = { /* code 01DC, LATIN SMALL LETTER U WITH DIAERESIS AND GRAVE */
  _X______,
  _X______,
  _X_X____,
  ________,
  ________,
  X__X____,
  X__X____,
  X__X____,
  X__X____,
  XXXX____};

/* Start of unicode area <IPA Extensions> */
GUI_CONST_STORAGE unsigned char acGUI_FontLight16_0251[  6] = { /* code 0251, LATIN SMALL LETTER ALPHA */
  _XXX_X__,
  XX_XX___,
  X___X___,
  X___X___,
  X__XX___,
  _XXX_X__};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontLight16_53D8[ 20] = { /* code 53D8 */
  _____X__,________,
  XXXXXXXX,XXX_____,
  ____X_X_,________,
  __X_X_X_,X_______,
  XX__X_X_,_XX_____,
  _XXXXXXX,X_______,
  ___X___X,________,
  ____X_X_,________,
  ____XXX_,________,
  XXXX___X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_53EF[ 20] = { /* code 53EF */
  XXXXXXXX,XXX_____,
  ________,X_______,
  _XXXXX__,X_______,
  _X___X__,X_______,
  _X___X__,X_______,
  _X___X__,X_______,
  _XXXXX__,X_______,
  _X______,X_______,
  ________,X_______,
  ______XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_5668[ 20] = { /* code 5668 */
  _XXXX_XX,XX______,
  _X__X_X_,_X______,
  _XXXX_XX,XX______,
  _____X_X,________,
  _XXXXXXX,XXX_____,
  ____X_X_,________,
  XXXX___X,XXX_____,
  _XXXX_XX,XX______,
  _X__X_X_,_X______,
  _XXXX_XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_589E[ 20] = { /* code 589E */
  _____X__,X_______,
  _X__XXXX,XX______,
  XXX_XXX_,XX______,
  _X__XXXX,XX______,
  _X______,________,
  _X__XXXX,XX______,
  _X__X___,_X______,
  __XXXXXX,XX______,
  XX__X___,_X______,
  ____XXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_5927[ 20] = { /* code 5927 */
  _____X__,________,
  _____X__,________,
  _____X__,________,
  XXXXXXXX,XXX_____,
  _____X__,________,
  ____XX__,________,
  ____X_X_,________,
  ___X___X,________,
  __X_____,X_______,
  XX______,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_5BBD[ 20] = { /* code 5BBD */
  _____X__,________,
  _XXXXXXX,XX______,
  X__X___X,_X______,
  XXXXXXXX,XXX_____,
  ___X___X,________,
  _XXXXXXX,X_______,
  _X______,X_______,
  _X__XX__,X_X_____,
  ____XX__,__X_____,
  XXXX__XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_5E26[ 20] = { /* code 5E26 */
  __X__X__,X_______,
  XXXXXXXX,XXX_____,
  __X__X__,X_______,
  _XXXXXXX,XX______,
  ________,________,
  _____X__,________,
  __XXXXXX,X_______,
  __X__X__,X_______,
  __X__X_X,X_______,
  _____X__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_653E[ 20] = { /* code 653E */
  __X____X,________,
  __X___X_,________,
  XXXXX_XX,XXX_____,
  _X___XX_,_X______,
  __XXXXX_,_X______,
  _X__X_X_,X_______,
  _X__X__X,X_______,
  _X__X__X,________,
  _X__X_XX,X_______,
  X_XX_X__,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontLight16_76CA[ 20] = { /* code 76CA */
  __X_____,X_______,
  ___X___X,________,
  XXXXXXXX,XXX_____,
  ___X___X,________,
  __X_____,XX______,
  _X______,_X______,
  __XXXXXX,X_______,
  __X_X_X_,X_______,
  __X_X_X_,X_______,
  XXXXXXXX,XXX_____};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontLight16_CharInfo[141] = {
   {   1,   1,   0,  11,   6, acGUI_FontLight16_0020 } /* code 0020, SPACE */
  ,{   2,   8,   2,   3,   6, acGUI_FontLight16_0021 } /* code 0021, EXCLAMATION MARK */
  ,{   4,   3,   1,   3,   6, acGUI_FontLight16_0022 } /* code 0022, QUOTATION MARK */
  ,{   6,   7,   0,   4,   6, acGUI_FontLight16_0023 } /* code 0023, NUMBER SIGN */
  ,{   4,   9,   1,   3,   6, acGUI_FontLight16_0024 } /* code 0024, DOLLAR SIGN */
  ,{   6,   8,   0,   3,   6, acGUI_FontLight16_0025 } /* code 0025, PERCENT SIGN */
  ,{   6,   7,   0,   4,   6, acGUI_FontLight16_0026 } /* code 0026, AMPERSAND */
  ,{   2,   3,   2,   3,   6, acGUI_FontLight16_0027 } /* code 0027, APOSTROPHE */
  ,{   3,  10,   2,   3,   6, acGUI_FontLight16_0028 } /* code 0028, LEFT PARENTHESIS */
  ,{   3,  10,   1,   3,   6, acGUI_FontLight16_0029 } /* code 0029, RIGHT PARENTHESIS */
  ,{   4,   5,   1,   3,   6, acGUI_FontLight16_002A } /* code 002A, ASTERISK */
  ,{   6,   6,   0,   5,   6, acGUI_FontLight16_002B } /* code 002B, PLUS SIGN */
  ,{   3,   4,   1,   9,   6, acGUI_FontLight16_002C } /* code 002C, COMMA */
  ,{   4,   1,   1,   8,   6, acGUI_FontLight16_002D } /* code 002D, HYPHEN-MINUS */
  ,{   2,   2,   2,   9,   6, acGUI_FontLight16_002E } /* code 002E, FULL STOP */
  ,{   6,   8,   0,   3,   6, acGUI_FontLight16_002F } /* code 002F, SOLIDUS */
  ,{   6,   7,   0,   4,   6, acGUI_FontLight16_0030 } /* code 0030, DIGIT ZERO */
  ,{   4,   7,   1,   4,   6, acGUI_FontLight16_0031 } /* code 0031, DIGIT ONE */
  ,{   4,   7,   1,   4,   6, acGUI_FontLight16_0032 } /* code 0032, DIGIT TWO */
  ,{   4,   7,   1,   4,   6, acGUI_FontLight16_0033 } /* code 0033, DIGIT THREE */
  ,{   6,   7,   0,   4,   6, acGUI_FontLight16_0034 } /* code 0034, DIGIT FOUR */
  ,{   4,   7,   1,   4,   6, acGUI_FontLight16_0035 } /* code 0035, DIGIT FIVE */
  ,{   5,   7,   1,   4,   6, acGUI_FontLight16_0036 } /* code 0036, DIGIT SIX */
  ,{   4,   7,   1,   4,   6, acGUI_FontLight16_0037 } /* code 0037, DIGIT SEVEN */
  ,{   4,   7,   1,   4,   6, acGUI_FontLight16_0038 } /* code 0038, DIGIT EIGHT */
  ,{   4,   7,   1,   4,   6, acGUI_FontLight16_0039 } /* code 0039, DIGIT NINE */
  ,{   2,   5,   2,   6,   6, acGUI_FontLight16_003A } /* code 003A, COLON */
  ,{   3,   7,   1,   6,   6, acGUI_FontLight16_003B } /* code 003B, SEMICOLON */
  ,{   4,   6,   1,   5,   6, acGUI_FontLight16_003C } /* code 003C, LESS-THAN SIGN */
  ,{   4,   2,   1,   7,   6, acGUI_FontLight16_003D } /* code 003D, EQUALS SIGN */
  ,{   4,   6,   1,   5,   6, acGUI_FontLight16_003E } /* code 003E, GREATER-THAN SIGN */
  ,{   3,   8,   2,   3,   6, acGUI_FontLight16_003F } /* code 003F, QUESTION MARK */
  ,{   6,  10,   0,   3,   6, acGUI_FontLight16_0040 } /* code 0040, COMMERCIAL AT */
  ,{   6,   7,   0,   4,   6, acGUI_FontLight16_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{   4,   7,   1,   4,   6, acGUI_FontLight16_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{   5,   7,   0,   4,   6, acGUI_FontLight16_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{   5,   7,   1,   4,   6, acGUI_FontLight16_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{   4,   7,   1,   4,   6, acGUI_FontLight16_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{   4,   7,   1,   4,   6, acGUI_FontLight16_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{   5,   7,   0,   4,   6, acGUI_FontLight16_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{   4,   7,   1,   4,   6, acGUI_FontLight16_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   4,   7,   1,   4,   6, acGUI_FontLight16_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{   4,   7,   1,   4,   6, acGUI_FontLight16_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{   5,   7,   1,   4,   6, acGUI_FontLight16_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{   4,   7,   1,   4,   6, acGUI_FontLight16_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{   6,   7,   0,   4,   6, acGUI_FontLight16_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{   4,   7,   1,   4,   6, acGUI_FontLight16_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{   6,   7,   0,   4,   6, acGUI_FontLight16_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{   4,   7,   1,   4,   6, acGUI_FontLight16_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{   6,   9,   0,   4,   6, acGUI_FontLight16_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{   5,   7,   1,   4,   6, acGUI_FontLight16_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{   4,   7,   1,   4,   6, acGUI_FontLight16_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{   6,   7,   0,   4,   6, acGUI_FontLight16_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{   4,   7,   1,   4,   6, acGUI_FontLight16_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{   6,   7,   0,   4,   6, acGUI_FontLight16_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{   6,   7,   0,   4,   6, acGUI_FontLight16_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{   6,   7,   0,   4,   6, acGUI_FontLight16_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{   6,   7,   0,   4,   6, acGUI_FontLight16_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{   4,   7,   1,   4,   6, acGUI_FontLight16_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{   3,  10,   2,   3,   6, acGUI_FontLight16_005B } /* code 005B, LEFT SQUARE BRACKET */
  ,{   4,   9,   1,   3,   6, acGUI_FontLight16_005C } /* code 005C, REVERSE SOLIDUS */
  ,{   2,  10,   2,   3,   6, acGUI_FontLight16_005D } /* code 005D, RIGHT SQUARE BRACKET */
  ,{   4,   3,   1,   4,   6, acGUI_FontLight16_005E } /* code 005E, CIRCUMFLEX ACCENT */
  ,{   6,   1,   0,  12,   6, acGUI_FontLight16_005F } /* code 005F, LOW LINE */
  ,{   1,   2,   1,   3,   3, acGUI_FontLight16_0060 } /* code 0060, GRAVE ACCENT */
  ,{   4,   5,   1,   6,   6, acGUI_FontLight16_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{   4,   8,   1,   3,   6, acGUI_FontLight16_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{   4,   5,   1,   6,   6, acGUI_FontLight16_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{   4,   8,   1,   3,   6, acGUI_FontLight16_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{   4,   5,   1,   6,   6, acGUI_FontLight16_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{   6,   8,   0,   3,   6, acGUI_FontLight16_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{   6,   7,   0,   6,   6, acGUI_FontLight16_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{   4,   8,   1,   3,   6, acGUI_FontLight16_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   4,   8,   1,   3,   6, acGUI_FontLight16_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   4,  10,   1,   3,   6, acGUI_FontLight16_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{   5,   8,   1,   3,   6, acGUI_FontLight16_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   4,   8,   1,   3,   6, acGUI_FontLight16_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{   6,   5,   0,   6,   6, acGUI_FontLight16_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{   4,   5,   1,   6,   6, acGUI_FontLight16_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{   6,   5,   0,   6,   6, acGUI_FontLight16_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{   4,   7,   1,   6,   6, acGUI_FontLight16_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{   4,   7,   1,   6,   6, acGUI_FontLight16_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{   5,   5,   1,   6,   6, acGUI_FontLight16_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{   4,   5,   1,   6,   6, acGUI_FontLight16_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   5,   7,   0,   4,   6, acGUI_FontLight16_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{   4,   5,   1,   6,   6, acGUI_FontLight16_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{   6,   5,   0,   6,   6, acGUI_FontLight16_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{   6,   5,   0,   6,   6, acGUI_FontLight16_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{   6,   5,   0,   6,   6, acGUI_FontLight16_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{   6,   7,   0,   6,   6, acGUI_FontLight16_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{   4,   5,   1,   6,   6, acGUI_FontLight16_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{   4,  10,   1,   3,   6, acGUI_FontLight16_007B } /* code 007B, LEFT CURLY BRACKET */
  ,{   1,  11,   3,   2,   6, acGUI_FontLight16_007C } /* code 007C, VERTICAL LINE */
  ,{   4,  10,   1,   3,   6, acGUI_FontLight16_007D } /* code 007D, RIGHT CURLY BRACKET */
  ,{   6,   2,   0,   7,   6, acGUI_FontLight16_007E } /* code 007E, TILDE */
  ,{   5,   7,   1,   3,   7, acGUI_FontLight16_00A4 } /* code 00A4, CURRENCY SIGN */
  ,{   4,   9,   1,   2,   5, acGUI_FontLight16_00A7 } /* code 00A7, SECTION SIGN */
  ,{   3,   1,   1,   3,   5, acGUI_FontLight16_00A8 } /* code 00A8, DIAERESIS */
  ,{   3,   3,   1,   3,   4, acGUI_FontLight16_00B0 } /* code 00B0, DEGREE SIGN */
  ,{   5,   7,   2,   4,   8, acGUI_FontLight16_00B1 } /* code 00B1, PLUS-MINUS SIGN */
  ,{   1,   1,   1,   7,   3, acGUI_FontLight16_00B7 } /* code 00B7, MIDDLE DOT */
  ,{   5,   5,   2,   5,   8, acGUI_FontLight16_00D7 } /* code 00D7, MULTIPLICATION SIGN */
  ,{   4,   8,   1,   3,   6, acGUI_FontLight16_00E0 } /* code 00E0, LATIN SMALL LETTER A WITH GRAVE */
  ,{   4,   9,   1,   2,   6, acGUI_FontLight16_00E1 } /* code 00E1, LATIN SMALL LETTER A WITH ACUTE */
  ,{   4,  10,   1,   1,   6, acGUI_FontLight16_00E8 } /* code 00E8, LATIN SMALL LETTER E WITH GRAVE */
  ,{   4,  11,   1,   0,   6, acGUI_FontLight16_00E9 } /* code 00E9, LATIN SMALL LETTER E WITH ACUTE */
  ,{   4,   9,   1,   2,   6, acGUI_FontLight16_00EA } /* code 00EA, LATIN SMALL LETTER E WITH CIRCUMFLEX */
  ,{   1,   9,   1,   2,   3, acGUI_FontLight16_00EC } /* code 00EC, LATIN SMALL LETTER I WITH GRAVE */
  ,{   2,   9,   1,   2,   3, acGUI_FontLight16_00ED } /* code 00ED, LATIN SMALL LETTER I WITH ACUTE */
  ,{   6,   8,   0,   3,   6, acGUI_FontLight16_00F2 } /* code 00F2, LATIN SMALL LETTER O WITH GRAVE */
  ,{   6,   9,   0,   2,   6, acGUI_FontLight16_00F3 } /* code 00F3, LATIN SMALL LETTER O WITH ACUTE */
  ,{   5,   5,   1,   5,   8, acGUI_FontLight16_00F7 } /* code 00F7, DIVISION SIGN */
  ,{   4,   8,   1,   3,   6, acGUI_FontLight16_00F9 } /* code 00F9, LATIN SMALL LETTER U WITH GRAVE */
  ,{   4,   9,   1,   2,   6, acGUI_FontLight16_00FA } /* code 00FA, LATIN SMALL LETTER U WITH ACUTE */
  ,{   4,   7,   1,   4,   6, acGUI_FontLight16_00FC } /* code 00FC, LATIN SMALL LETTER U WITH DIAERESIS */
  ,{   5,   8,   1,   3,   6, acGUI_FontLight16_0101 } /* code 0101, LATIN SMALL LETTER A WITH MACRON */
  ,{   5,  10,   0,   1,   6, acGUI_FontLight16_0113 } /* code 0113, LATIN SMALL LETTER E WITH MACRON */
  ,{   4,  11,   1,   0,   6, acGUI_FontLight16_011B } /* code 011B, LATIN SMALL LETTER E WITH CARON */
  ,{   4,   8,   0,   3,   3, acGUI_FontLight16_012B } /* code 012B, LATIN SMALL LETTER I WITH MACRON */
  ,{   5,   9,   1,   2,   6, acGUI_FontLight16_0144 } /* code 0144, LATIN SMALL LETTER N WITH ACUTE */
  ,{   5,   9,   1,   2,   6, acGUI_FontLight16_0148 } /* code 0148, LATIN SMALL LETTER N WITH CARON */
  ,{   7,   8,   0,   3,   6, acGUI_FontLight16_014D } /* code 014D, LATIN SMALL LETTER O WITH MACRON */
  ,{   5,   8,   0,   3,   6, acGUI_FontLight16_016B } /* code 016B, LATIN SMALL LETTER U WITH MACRON */
  ,{   4,   9,   1,   2,   6, acGUI_FontLight16_01CE } /* code 01CE, LATIN SMALL LETTER A WITH CARON */
  ,{   3,   9,   0,   2,   3, acGUI_FontLight16_01D0 } /* code 01D0, LATIN SMALL LETTER I WITH CARON */
  ,{   6,   9,   0,   2,   6, acGUI_FontLight16_01D2 } /* code 01D2, LATIN SMALL LETTER O WITH CARON */
  ,{   4,   9,   1,   2,   6, acGUI_FontLight16_01D4 } /* code 01D4, LATIN SMALL LETTER U WITH CARON */
  ,{   4,  10,   1,   1,   6, acGUI_FontLight16_01D6 } /* code 01D6, LATIN SMALL LETTER U WITH DIAERESIS AND MACRON */
  ,{   4,  11,   1,   0,   6, acGUI_FontLight16_01D8 } /* code 01D8, LATIN SMALL LETTER U WITH DIAERESIS AND ACUTE */
  ,{   4,  11,   1,   0,   6, acGUI_FontLight16_01DA } /* code 01DA, LATIN SMALL LETTER U WITH DIAERESIS AND CARON */
  ,{   4,  10,   1,   1,   6, acGUI_FontLight16_01DC } /* code 01DC, LATIN SMALL LETTER U WITH DIAERESIS AND GRAVE */
  ,{   6,   6,   1,   5,   7, acGUI_FontLight16_0251 } /* code 0251, LATIN SMALL LETTER ALPHA */
  ,{  11,  10,   0,   2,  11, acGUI_FontLight16_53D8 } /* code 53D8 */
  ,{  11,  10,   0,   2,  11, acGUI_FontLight16_53EF } /* code 53EF */
  ,{  11,  10,   0,   2,  11, acGUI_FontLight16_5668 } /* code 5668 */
  ,{  10,  10,   0,   2,  11, acGUI_FontLight16_589E } /* code 589E */
  ,{  11,  10,   0,   2,  11, acGUI_FontLight16_5927 } /* code 5927 */
  ,{  11,  10,   0,   2,  11, acGUI_FontLight16_5BBD } /* code 5BBD */
  ,{  11,  10,   0,   2,  11, acGUI_FontLight16_5E26 } /* code 5E26 */
  ,{  11,  10,   0,   2,  11, acGUI_FontLight16_653E } /* code 653E */
  ,{  11,  10,   0,   2,  11, acGUI_FontLight16_76CA } /* code 76CA */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop39 = {
   0x76CA /* first character */
  ,0x76CA /* last character  */
  ,&GUI_FontLight16_CharInfo[140] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop38 = {
   0x653E /* first character */
  ,0x653E /* last character  */
  ,&GUI_FontLight16_CharInfo[139] /* address of first character */
  ,&GUI_FontLight16_Prop39 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop37 = {
   0x5E26 /* first character */
  ,0x5E26 /* last character  */
  ,&GUI_FontLight16_CharInfo[138] /* address of first character */
  ,&GUI_FontLight16_Prop38 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop36 = {
   0x5BBD /* first character */
  ,0x5BBD /* last character  */
  ,&GUI_FontLight16_CharInfo[137] /* address of first character */
  ,&GUI_FontLight16_Prop37 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop35 = {
   0x5927 /* first character */
  ,0x5927 /* last character  */
  ,&GUI_FontLight16_CharInfo[136] /* address of first character */
  ,&GUI_FontLight16_Prop36 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop34 = {
   0x589E /* first character */
  ,0x589E /* last character  */
  ,&GUI_FontLight16_CharInfo[135] /* address of first character */
  ,&GUI_FontLight16_Prop35 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop33 = {
   0x5668 /* first character */
  ,0x5668 /* last character  */
  ,&GUI_FontLight16_CharInfo[134] /* address of first character */
  ,&GUI_FontLight16_Prop34 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop32 = {
   0x53EF /* first character */
  ,0x53EF /* last character  */
  ,&GUI_FontLight16_CharInfo[133] /* address of first character */
  ,&GUI_FontLight16_Prop33 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop31 = {
   0x53D8 /* first character */
  ,0x53D8 /* last character  */
  ,&GUI_FontLight16_CharInfo[132] /* address of first character */
  ,&GUI_FontLight16_Prop32 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop30 = {
   0x0251 /* first character */
  ,0x0251 /* last character  */
  ,&GUI_FontLight16_CharInfo[131] /* address of first character */
  ,&GUI_FontLight16_Prop31 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop29 = {
   0x01DC /* first character */
  ,0x01DC /* last character  */
  ,&GUI_FontLight16_CharInfo[130] /* address of first character */
  ,&GUI_FontLight16_Prop30 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop28 = {
   0x01DA /* first character */
  ,0x01DA /* last character  */
  ,&GUI_FontLight16_CharInfo[129] /* address of first character */
  ,&GUI_FontLight16_Prop29 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop27 = {
   0x01D8 /* first character */
  ,0x01D8 /* last character  */
  ,&GUI_FontLight16_CharInfo[128] /* address of first character */
  ,&GUI_FontLight16_Prop28 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop26 = {
   0x01D6 /* first character */
  ,0x01D6 /* last character  */
  ,&GUI_FontLight16_CharInfo[127] /* address of first character */
  ,&GUI_FontLight16_Prop27 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop25 = {
   0x01D4 /* first character */
  ,0x01D4 /* last character  */
  ,&GUI_FontLight16_CharInfo[126] /* address of first character */
  ,&GUI_FontLight16_Prop26 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop24 = {
   0x01D2 /* first character */
  ,0x01D2 /* last character  */
  ,&GUI_FontLight16_CharInfo[125] /* address of first character */
  ,&GUI_FontLight16_Prop25 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop23 = {
   0x01D0 /* first character */
  ,0x01D0 /* last character  */
  ,&GUI_FontLight16_CharInfo[124] /* address of first character */
  ,&GUI_FontLight16_Prop24 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop22 = {
   0x01CE /* first character */
  ,0x01CE /* last character  */
  ,&GUI_FontLight16_CharInfo[123] /* address of first character */
  ,&GUI_FontLight16_Prop23 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop21 = {
   0x016B /* first character */
  ,0x016B /* last character  */
  ,&GUI_FontLight16_CharInfo[122] /* address of first character */
  ,&GUI_FontLight16_Prop22 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop20 = {
   0x014D /* first character */
  ,0x014D /* last character  */
  ,&GUI_FontLight16_CharInfo[121] /* address of first character */
  ,&GUI_FontLight16_Prop21 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop19 = {
   0x0148 /* first character */
  ,0x0148 /* last character  */
  ,&GUI_FontLight16_CharInfo[120] /* address of first character */
  ,&GUI_FontLight16_Prop20 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop18 = {
   0x0144 /* first character */
  ,0x0144 /* last character  */
  ,&GUI_FontLight16_CharInfo[119] /* address of first character */
  ,&GUI_FontLight16_Prop19 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop17 = {
   0x012B /* first character */
  ,0x012B /* last character  */
  ,&GUI_FontLight16_CharInfo[118] /* address of first character */
  ,&GUI_FontLight16_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop16 = {
   0x011B /* first character */
  ,0x011B /* last character  */
  ,&GUI_FontLight16_CharInfo[117] /* address of first character */
  ,&GUI_FontLight16_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop15 = {
   0x0113 /* first character */
  ,0x0113 /* last character  */
  ,&GUI_FontLight16_CharInfo[116] /* address of first character */
  ,&GUI_FontLight16_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop14 = {
   0x0101 /* first character */
  ,0x0101 /* last character  */
  ,&GUI_FontLight16_CharInfo[115] /* address of first character */
  ,&GUI_FontLight16_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop13 = {
   0x00FC /* first character */
  ,0x00FC /* last character  */
  ,&GUI_FontLight16_CharInfo[114] /* address of first character */
  ,&GUI_FontLight16_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop12 = {
   0x00F9 /* first character */
  ,0x00FA /* last character  */
  ,&GUI_FontLight16_CharInfo[112] /* address of first character */
  ,&GUI_FontLight16_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop11 = {
   0x00F7 /* first character */
  ,0x00F7 /* last character  */
  ,&GUI_FontLight16_CharInfo[111] /* address of first character */
  ,&GUI_FontLight16_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop10 = {
   0x00F2 /* first character */
  ,0x00F3 /* last character  */
  ,&GUI_FontLight16_CharInfo[109] /* address of first character */
  ,&GUI_FontLight16_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop9 = {
   0x00EC /* first character */
  ,0x00ED /* last character  */
  ,&GUI_FontLight16_CharInfo[107] /* address of first character */
  ,&GUI_FontLight16_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop8 = {
   0x00E8 /* first character */
  ,0x00EA /* last character  */
  ,&GUI_FontLight16_CharInfo[104] /* address of first character */
  ,&GUI_FontLight16_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop7 = {
   0x00E0 /* first character */
  ,0x00E1 /* last character  */
  ,&GUI_FontLight16_CharInfo[102] /* address of first character */
  ,&GUI_FontLight16_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop6 = {
   0x00D7 /* first character */
  ,0x00D7 /* last character  */
  ,&GUI_FontLight16_CharInfo[101] /* address of first character */
  ,&GUI_FontLight16_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop5 = {
   0x00B7 /* first character */
  ,0x00B7 /* last character  */
  ,&GUI_FontLight16_CharInfo[100] /* address of first character */
  ,&GUI_FontLight16_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop4 = {
   0x00B0 /* first character */
  ,0x00B1 /* last character  */
  ,&GUI_FontLight16_CharInfo[ 98] /* address of first character */
  ,&GUI_FontLight16_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop3 = {
   0x00A7 /* first character */
  ,0x00A8 /* last character  */
  ,&GUI_FontLight16_CharInfo[ 96] /* address of first character */
  ,&GUI_FontLight16_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop2 = {
   0x00A4 /* first character */
  ,0x00A4 /* last character  */
  ,&GUI_FontLight16_CharInfo[ 95] /* address of first character */
  ,&GUI_FontLight16_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontLight16_Prop1 = {
   0x0020 /* first character */
  ,0x007E /* last character  */
  ,&GUI_FontLight16_CharInfo[  0] /* address of first character */
  ,&GUI_FontLight16_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontLight16 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,14 /* height of font  */
  ,14 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontLight16_Prop1}
  ,11 /* Baseline */
  ,5 /* Height of lowercase characters */
  ,7 /* Height of capital characters */
};

