/*********************************************************************
 *                                                                    *
 *                SEGGER Microcontroller GmbH & Co. KG                *
 *        Solutions for real time microcontroller applications        *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 * C-file generated by:                                               *
 *                                                                    *
 *        GUI_Builder for emWin version 5.30                          *
 *        Compiled Jul  1 2015, 10:50:32                              *
 *        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 *        Internet: www.segger.com  Support: support@segger.com       *
 *                                                                    *
 **********************************************************************
 */

// USER START (Optionally insert additional includes)

#include <stdio.h>
#include <string.h>
#include "../../rtc/rtc.h"
#include <time.h>
// USER END

#include "DIALOG.h"

/*********************************************************************
 *
 *       Defines
 *
 **********************************************************************
 */
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)
#define ID_EDIT_0 (GUI_ID_USER + 0x01)
#define ID_EDIT_1 (GUI_ID_USER + 0x02)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
 *
 *       Static data
 *
 **********************************************************************
 */

// USER START (Optionally insert additional static data)
// USER END
/*********************************************************************
 *
 *       _aDialogCreate
 */
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
		{FRAMEWIN_CreateIndirect, "2130504041 2130504046", ID_FRAMEWIN_0, 0, 0,320, 240, 0, 0x0, 0 },
		{ EDIT_CreateIndirect, "Edit", ID_EDIT_0, 33, 16,   248, 43, 0, 0x64, 0 },
		{ EDIT_CreateIndirect, "Edit", ID_EDIT_1, 33, 16+44,248, 43, 0, 0x64, 0 },
		// USER START (Optionally insert additional widgets)
		// USER END
		};

/*********************************************************************
 *
 *       Static code
 *
 **********************************************************************
 */

// USER START (Optionally insert additional static code)
// USER END
/*********************************************************************
 *
 *       _cbDialog
 */
static void _cbDialog(WM_MESSAGE * pMsg) {
	WM_HWIN hItem;
	int NCode;
	int Id;
	// USER START (Optionally insert additional variables)
	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
	char buf[64];
	WM_SetFocus(hItem);
	// USER END

	switch (pMsg->MsgId) {
	case WM_INIT_DIALOG:
		//
		// Initialization of 'Edit'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		EDIT_SetText(hItem, "2016 10 22 13 44 1");
		EDIT_SetFont(hItem, GUI_FONT_24_ASCII);
		// USER START (Optionally insert additional code for further widget initialization)
		// USER END
		break;
	case WM_NOTIFY_PARENT:
		Id = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;
		switch (Id) {
		case ID_EDIT_0: // Notifications sent by 'Edit'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
			// USER START (Optionally insert additional code for further Ids)
			// USER END
		}
		break;
		// USER START (Optionally insert additional message handling)
	case WM_KEY:
		switch (((WM_KEY_INFO*) (pMsg->Data.p))->Key) {
		case GUI_KEY_ENTER:
			hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);

			EDIT_GetText(hItem, buf, 64);
			{
				char cc;
				int a,b;
				struct tm tm_tm;

				int r;
				if((sscanf(buf,"%d%c%d",&a,&cc,&b)==3) && (cc != ' ')){
					switch(cc){
					case '+':r = a +b;sprintf(buf,"%d",r);break;
					case '-':r=a-b;sprintf(buf,"%d",r);break;
					case 'x':r=a*b;sprintf(buf,"%d",r);break;
					case '/':r=a/b;sprintf(buf,"%d",r);break;
					}
					EDIT_SetText(hItem, buf);
				}else if(sscanf(buf,"%d %d %d %d %d %d",
						&(tm_tm.tm_year),
						&tm_tm.tm_mon,
						&tm_tm.tm_mday,
						&tm_tm.tm_hour,
						&tm_tm.tm_min,
						&tm_tm.tm_sec)==6)
				{
					time_t tim  =  my_mktime(tm_tm.tm_year,
								tm_tm.tm_mon,
								tm_tm.tm_mday,
								tm_tm.tm_hour,
								tm_tm.tm_min,
								tm_tm.tm_sec);
//					time_t tim  =  my_mktime(2016,10,22,13,49,1);
						void setTime_t(time_t tm);
						setTime_t(tim);
				}else if(strlen(buf)==1 &&(buf[0] == '5')){
					void Audio_PlayTest(int nDevice);
					Audio_PlayTest(0);
				}

			}

			{
				hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
				EDIT_GetText(hItem, buf, 64);

			}
			break;
		case GUI_KEY_END:
			hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
			EDIT_GetText(hItem, buf, 64);
			{
				RTC_TIME rtc_data={
						.tm_year = 16,
						.tm_week = SATURDAY,
						.tm_mon = 10,
						.tm_mday = 22,
						.tm_hour = 11,
						.tm_min = 17,
						.tm_sec = 17,
				};

				rtcwrite(rtc_data,1);
			}
			break;
		}
		break;
		// USER END
	default:
		WM_DefaultProc(pMsg);
		break;
	}
}

/*********************************************************************
 *
 *       Public code
 *
 **********************************************************************
 */
/*********************************************************************
 *
 *       CreateFramewin
 */
static WM_HWIN hWin;
WM_HWIN CreateFramewin(void);
WM_HWIN CreateFramewin(void) {
	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate),
			_cbDialog, WM_HBKWIN, 0, 0);
	return hWin;
}

// USER START (Optionally insert additional public code)

void LineEditSetText(const char* p){
	WM_HWIN hItem = WM_GetDialogItem(hWin, ID_EDIT_0);
	EDIT_SetText(hItem, p);
}
// USER END

/*************************** End of file ****************************/
