///*
// *
//These function attributes are supported for ARM targets:
//
//interrupt
//Use this attribute to indicate that the specified function is an interrupt handler. The compiler generates function entry and exit sequences suitable for use in an interrupt handler when this attribute is present.
//You can specify the kind of interrupt to be handled by adding an optional parameter to the interrupt attribute like this:
//
//          void f () __attribute__ ((interrupt ("IRQ")));
//Permissible values for this parameter are: IRQ, FIQ, SWI, ABORT and UNDEF.
//
//On ARMv7-M the interrupt type is ignored, and the attribute means the function may be called with a word-aligned stack pointer.
//
//isr
//Use this attribute on ARM to write Interrupt Service Routines. This is an alias to the interrupt attribute above.
//long_call
//short_call
//These attributes specify how a particular function is called. These attributes override the -mlong-calls (see ARM Options) command-line switch and #pragma long_calls settings. For ARM, the long_call attribute indicates that the function might be far away from the call site and require a different (more expensive) calling sequence. The short_call attribute always places the offset to the function from the call site into the ¡®BL¡¯ instruction directly.
//naked
//This attribute allows the compiler to construct the requisite function declaration, while allowing the body of the function to be assembly code. The specified function will not have prologue/epilogue sequences generated by the compiler. Only basic asm statements can safely be included in naked functions (see Basic Asm). While using extended asm or a mixture of basic asm and C code may appear to work, they cannot be depended upon to work reliably and are not supported.
//pcs
//The pcs attribute can be used to control the calling convention used for a function on ARM. The attribute takes an argument that specifies the calling convention to use.
//When compiling using the AAPCS ABI (or a variant of it) then valid values for the argument are "aapcs" and "aapcs-vfp". In order to use a variant other than "aapcs" then the compiler must be permitted to use the appropriate co-processor registers (i.e., the VFP registers must be available in order to use "aapcs-vfp"). For example,
//
//          /* Argument passed in r0, and result returned in r0+r1.  */
//          double f2d (float) __attribute__((pcs("aapcs")));
//Variadic functions always use the "aapcs" calling convention and the compiler rejects attempts to specify an alternative.
//
//target (options)
//As discussed in Common Function Attributes, this attribute allows specification of target-specific compilation options.
//On ARM, the following options are allowed:
//
//¡®thumb¡¯
//Force code generation in the Thumb (T16/T32) ISA, depending on the architecture level.
//¡®arm¡¯
//Force code generation in the ARM (A32) ISA.
//Functions from different modes can be inlined in the caller's mode.
//
//¡®fpu=¡¯
//Specifies the fpu for which to tune the performance of this function. The behavior and permissible arguments are the same as for the -mfpu= command-line option. *
// */
#include <stdint.h>

//*****************************************************************************
//
// Forward declaration of the default fault handlers.
//
//*****************************************************************************
extern void ResetISR(void);
static void UndefinedISR(void){
	while(1);
}
static void SVCISR(void){
	while(1);

}
static void DefaultISR(void){

	__asm("b .");
}
extern void IRQ_Handler(void);
void c_IRQ_Handler(void){
	IRQ_Handler();
}

static void FIQ_Handler(void){
	while(1);

}
//*****************************************************************************
//
// External declarations for the interrupt handlers used by the application.
//
//*****************************************************************************


//*****************************************************************************
//
// The entry point for the application.
//
//*****************************************************************************
extern int main(void);

//*****************************************************************************
//
// The vector table.  Note that the proper constructs must be placed on this to
// ensure that it ends up at physical address 0x0000.0000.
//
//*****************************************************************************
//__attribute__ ((section(".isr_vector")))
//void (* const g_pfnVectors[])(void) =
//{
//		ResetISR,
//		UndefinedISR,
//		SVCISR,
//		DefaultISR,
//		DefaultISR,
//		DefaultISR,
//		c_IRQ_Handler,
//		FIQ_Handler
//};

//*****************************************************************************
//
// The following are constructs created by the linker, indicating where the
// the "data" and "bss" segments reside in memory.  The initializers for the
// for the "data" segment resides immediately following the "text" segment.
//
//*****************************************************************************

void ResetISR_C(void)
{
	extern void _start();
	 __asm volatile("MSR CPSR_c, #0x10");
//	(*((unsigned int * )(0x18))) = (unsigned int)&IRQ_Handler;
	_start();
    main();
}

